-- IMC-DB-001-22. Execute each target ONLY via Database Manager plan_migration/execute_migration.
-- BEFORE means inside MySQL after request arrival, before raw row persistence and all AFTER Site/report triggers.
-- Only competition_key changes. No importer or other repository changes.
-- TARGET gold; migration_id IMC-DB-001-22-gold-normalize-v1
CREATE TRIGGER `trg_GW002_results_playoff_bi` BEFORE INSERT ON `GW002_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW002_results_playoff_bu` BEFORE UPDATE ON `GW002_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW003_results_playoff_bi` BEFORE INSERT ON `GW003_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW003_results_playoff_bu` BEFORE UPDATE ON `GW003_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW007_results_playoff_bi` BEFORE INSERT ON `GW007_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW007_results_playoff_bu` BEFORE UPDATE ON `GW007_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW008_results_playoff_bi` BEFORE INSERT ON `GW008_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW008_results_playoff_bu` BEFORE UPDATE ON `GW008_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

-- TARGET custom; migration_id IMC-DB-001-22-custom-normalize-v1
CREATE TRIGGER `trg_GW001_results_playoff_bi` BEFORE INSERT ON `GW001_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW001_results_playoff_bu` BEFORE UPDATE ON `GW001_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW004_results_playoff_bi` BEFORE INSERT ON `GW004_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW004_results_playoff_bu` BEFORE UPDATE ON `GW004_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW005_results_playoff_bi` BEFORE INSERT ON `GW005_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW005_results_playoff_bu` BEFORE UPDATE ON `GW005_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW006_results_playoff_bi` BEFORE INSERT ON `GW006_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW006_results_playoff_bu` BEFORE UPDATE ON `GW006_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW009_results_playoff_bi` BEFORE INSERT ON `GW009_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

CREATE TRIGGER `trg_GW009_results_playoff_bu` BEFORE UPDATE ON `GW009_IMC Results` FOR EACH ROW SET NEW.competition_key=CASE WHEN (REGEXP_LIKE(TRIM(COALESCE(NEW.sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(NEW.competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) THEN CONCAT_WS('|',NEW.game_world_id,CASE WHEN UPPER(TRIM(COALESCE(NEW.sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(NEW.sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(NEW.sm_division),'')) ELSE NEW.competition_key END;

-- TARGET custom; existing rows after DDL verified.
-- Self-assignment deliberately leaves the incoming League key intact: BEFORE UPDATE performs normalization.
UPDATE `GW001_IMC Results` SET competition_key=competition_key WHERE (REGEXP_LIKE(TRIM(COALESCE(sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) AND NOT(competition_key <=> CONCAT_WS('|',game_world_id,CASE WHEN UPPER(TRIM(COALESCE(sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(sm_division),'')));

UPDATE `GW005_IMC Results` SET competition_key=competition_key WHERE (REGEXP_LIKE(TRIM(COALESCE(sm_action,'')), '^play[[:space:]-]*offs?$', 'i') OR REGEXP_LIKE(TRIM(COALESCE(competition_stage,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(competition_group_name,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i') OR REGEXP_LIKE(TRIM(COALESCE(competition_round,'')), '^play[[:space:]-]*offs?([[:space:]:-]|$)', 'i')) AND NOT(competition_key <=> CONCAT_WS('|',game_world_id,CASE WHEN UPPER(TRIM(COALESCE(sm_country,''))) IN ('','CUS') THEN NULL ELSE UPPER(TRIM(sm_country)) END,'DOMESTIC','playoff',NULLIF(TRIM(sm_division),'')));
